type playlistTracksGroup = {
    tracks: playlistItems;
};

type playlistItems = {
    items: [playlistTracks]
}
type playlistTracks = {
    track: plalistSongData;
};

type plalistSongData = {
    id: string;
};

/*"tracks": {
    "items": [
        {
            "added_at": "2023-04-09T01:24:35Z",
            "added_by": {
                "external_urls": {
                    "spotify": "https://open.spotify.com/user/31fdzimdkqbxvsdui3ubqryilkbm"
                },
                "href": "https://api.spotify.com/v1/users/31fdzimdkqbxvsdui3ubqryilkbm",
                "id": "31fdzimdkqbxvsdui3ubqryilkbm",
                "type": "user",
                "uri": "spotify:user:31fdzimdkqbxvsdui3ubqryilkbm"
            },
            "is_local": false,
            "primary_color": null,
            "track": {
                "album": {
                    "album_group": "album",
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/1tBs3dNmfFvNiis6PPhzGa"
                            },
                            "href": "https://api.spotify.com/v1/artists/1tBs3dNmfFvNiis6PPhzGa",
                            "id": "1tBs3dNmfFvNiis6PPhzGa",
                            "name": "SONIC HEROES",
                            "type": "artist",
                            "uri": "spotify:artist:1tBs3dNmfFvNiis6PPhzGa"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/2nFhRH7h4P1Lh9qrhowHJ0"
                    },
                    "href": "https://api.spotify.com/v1/albums/2nFhRH7h4P1Lh9qrhowHJ0",
                    "id": "2nFhRH7h4P1Lh9qrhowHJ0",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b2732f95e7dc6e64203b4158d3c5",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e022f95e7dc6e64203b4158d3c5",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d000048512f95e7dc6e64203b4158d3c5",
                            "width": 64
                        }
                    ],
                    "is_playable": true,
                    "name": "SONIC HEROES Original Soundtrack (20th Anniversary Edition)",
                    "release_date": "2011-08-24",
                    "release_date_precision": "day",
                    "total_tracks": 30,
                    "type": "album",
                    "uri": "spotify:album:2nFhRH7h4P1Lh9qrhowHJ0"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4gNEgDZhEu6ldAI2wWdZsL"
                        },
                        "href": "https://api.spotify.com/v1/artists/4gNEgDZhEu6ldAI2wWdZsL",
                        "id": "4gNEgDZhEu6ldAI2wWdZsL",
                        "name": "Crush 40",
                        "type": "artist",
                        "uri": "spotify:artist:4gNEgDZhEu6ldAI2wWdZsL"
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK"
                ],
                "disc_number": 1,
                "duration_ms": 95906,
                "episode": false,
                "explicit": false,
                "external_ids": {
                    "isrc": "JPX300301820"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4ox9bVhcskrvPgnBWFwyaq"
                },
                "href": "https://api.spotify.com/v1/tracks/4ox9bVhcskrvPgnBWFwyaq",
                "id": "4ox9bVhcskrvPgnBWFwyaq",
                "is_local": false,
                "name": "Sonic Heroes: Main Theme of Sonic Heroes",
                "popularity": 44,
                "preview_url": "https://p.scdn.co/mp3-preview/a298ba4b040086ec9026ea2a8c595ea0bfe353a2?cid=cfe923b2d660439caf2b557b21f31221",
                "track": true,
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:4ox9bVhcskrvPgnBWFwyaq"
            },
            "video_thumbnail": {
                "url": null
            }
        }
  }*/